"""empty message

Revision ID: 029127bac94c
Revises: a35716e87c02
Create Date: 2022-05-24 15:53:11.492494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029127bac94c'
down_revision = 'a35716e87c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('endpoint', sa.String(length=500), nullable=False))
    op.drop_column('endpoints', 'endponit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('endponit', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('endpoints', 'endpoint')
    # ### end Alembic commands ###
