"""empty message

Revision ID: 0d5c016557a4
Revises: 6ccb841a5869
Create Date: 2022-07-19 11:15:23.862417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5c016557a4'
down_revision = '6ccb841a5869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('endpoints', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'endpoints', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'endpoints', 'users', ['modified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'endpoints', type_='foreignkey')
    op.drop_constraint(None, 'endpoints', type_='foreignkey')
    op.drop_column('endpoints', 'modified_by')
    op.drop_column('endpoints', 'created_by')
    # ### end Alembic commands ###
