"""empty message

Revision ID: 11d3b1245f76
Revises: 069163ba3fc5
Create Date: 2022-05-29 13:41:18.381047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d3b1245f76'
down_revision = '069163ba3fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcases', sa.Column('endpoint', sa.Integer(), nullable=False))
    op.drop_constraint('testcases_endponit_fkey', 'testcases', type_='foreignkey')
    op.create_foreign_key(None, 'testcases', 'endpoints', ['endpoint'], ['id'])
    op.drop_column('testcases', 'endponit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcases', sa.Column('endponit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'testcases', type_='foreignkey')
    op.create_foreign_key('testcases_endponit_fkey', 'testcases', 'endpoints', ['endponit'], ['id'])
    op.drop_column('testcases', 'endpoint')
    # ### end Alembic commands ###
