"""empty message

Revision ID: 22cd44943c2a
Revises: 11d3b1245f76
Create Date: 2022-05-29 17:47:23.048066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cd44943c2a'
down_revision = '11d3b1245f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('payload_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.ForeignKeyConstraint(['header_id'], ['headers.id'], ),
    sa.ForeignKeyConstraint(['payload_id'], ['payloads.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key(None, 'testdata', 'testcases', ['testcase'], ['id'])
    op.create_foreign_key(None, 'testsuite_testcase', 'testcases', ['testcase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testsuite_testcase', type_='foreignkey')
    op.drop_constraint(None, 'testdata', type_='foreignkey')
    op.drop_table('testcases')
    # ### end Alembic commands ###
