"""empty message

Revision ID: 293c34ca1e1e
Revises: 22cd44943c2a
Create Date: 2022-06-01 19:38:43.201183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293c34ca1e1e'
down_revision = '22cd44943c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testsuites', sa.Column('environment', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'testsuites', 'environments', ['environment'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testsuites', type_='foreignkey')
    op.drop_column('testsuites', 'environment')
    # ### end Alembic commands ###
