"""empty message

Revision ID: 2948ed11a0f6
Revises: ca03b7af9fa8
Create Date: 2022-07-19 16:25:51.608558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2948ed11a0f6'
down_revision = 'ca03b7af9fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('endpoints', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'endpoints', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'endpoints', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'endpoints', type_='foreignkey')
    op.drop_constraint(None, 'endpoints', type_='foreignkey')
    op.drop_column('endpoints', 'modified_by')
    op.drop_column('endpoints', 'created_by')
    # ### end Alembic commands ###
