"""empty message

Revision ID: 37057cf57d1a
Revises: 71cd3a533b04
Create Date: 2022-07-26 18:07:00.443353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37057cf57d1a'
down_revision = '71cd3a533b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('testsuites_environment_fkey', 'testsuites', type_='foreignkey')
    op.drop_column('testsuites', 'environment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testsuites', sa.Column('environment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('testsuites_environment_fkey', 'testsuites', 'environments', ['environment'], ['id'])
    # ### end Alembic commands ###
