"""empty message

Revision ID: 3a6f1d54702f
Revises: 1abf806f95b4
Create Date: 2022-07-25 15:05:22.013008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a6f1d54702f'
down_revision = '1abf806f95b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_member')
    op.drop_table('organization_admin')
    op.drop_table('organization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('organization_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='organization_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='organization_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('organization_admin',
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='organization_admin_admin_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='organization_admin_organization_id_fkey')
    )
    op.create_table('organization_member',
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name='organization_member_member_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='organization_member_organization_id_fkey')
    )
    # ### end Alembic commands ###
