"""empty message

Revision ID: 46b1ea22ec82
Revises: 
Create Date: 2022-10-06 15:58:39.764486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46b1ea22ec82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_admin', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_admin'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('header', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_member',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'member_id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('testcase', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('teststeps', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('environment', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('no_of_passed_teststeps', sa.Integer(), nullable=True),
    sa.Column('no_of_failed_teststeps', sa.Integer(), nullable=True),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('executed_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('execution_sequence', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expected_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Integer(), nullable=True),
    sa.Column('expected_outcome', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payload'], ['payloads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_by', sa.Integer(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('testcase', sa.Integer(), nullable=True),
    sa.Column('environment', sa.Integer(), nullable=True),
    sa.Column('frequency_type', sa.String(length=100), nullable=False),
    sa.Column('frequency', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date_time', sa.Float(), nullable=False),
    sa.Column('end_date_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['testcase'], ['testcases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_time_id', sa.String(length=256), nullable=False),
    sa.Column('testcase', sa.Integer(), nullable=True),
    sa.Column('teststep', sa.String(length=256), nullable=False),
    sa.Column('resp', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['testcase'], ['testcases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teststeps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=True),
    sa.Column('payload_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['header_id'], ['headers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payload_id'], ['payloads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testcase_teststep',
    sa.Column('testcase_id', sa.Integer(), nullable=True),
    sa.Column('teststep_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teststep_id'], ['teststeps.id'], ondelete='CASCADE')
    )
    op.create_table('testdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_outcome', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('teststep', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teststep'], ['teststeps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testcase_testdata',
    sa.Column('testcase_id', sa.Integer(), nullable=True),
    sa.Column('testdata_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['testdata_id'], ['testdata.id'], ondelete='CASCADE')
    )
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_table('testcase_testdata')
    op.drop_table('testdata')
    op.drop_table('testcase_teststep')
    op.drop_table('teststeps')
    op.drop_table('temp')
    op.drop_table('scheduler')
    op.drop_table('expected_outcome')
    op.drop_table('testcases')
    op.drop_table('results')
    op.drop_table('project_member')
    op.drop_table('payloads')
    op.drop_table('headers')
    op.drop_table('environments')
    op.drop_table('endpoints')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
