"""empty message

Revision ID: 49f4abdb8e8d
Revises: e6d54f35979a
Create Date: 2022-07-20 13:58:10.441890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f4abdb8e8d'
down_revision = 'e6d54f35979a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('environments', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'environments', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'environments', 'users', ['created_by'], ['id'])
    op.add_column('payloads', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('payloads', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payloads', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'payloads', 'users', ['modified_by'], ['id'])
    op.add_column('testcases', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('testcases', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'testcases', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'testcases', 'users', ['modified_by'], ['id'])
    op.add_column('testdata', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('testdata', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'testdata', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'testdata', 'users', ['created_by'], ['id'])
    op.add_column('testsuites', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('testsuites', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'testsuites', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'testsuites', 'users', ['modified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testsuites', type_='foreignkey')
    op.drop_constraint(None, 'testsuites', type_='foreignkey')
    op.drop_column('testsuites', 'modified_by')
    op.drop_column('testsuites', 'created_by')
    op.drop_constraint(None, 'testdata', type_='foreignkey')
    op.drop_constraint(None, 'testdata', type_='foreignkey')
    op.drop_column('testdata', 'modified_by')
    op.drop_column('testdata', 'created_by')
    op.drop_constraint(None, 'testcases', type_='foreignkey')
    op.drop_constraint(None, 'testcases', type_='foreignkey')
    op.drop_column('testcases', 'modified_by')
    op.drop_column('testcases', 'created_by')
    op.drop_constraint(None, 'payloads', type_='foreignkey')
    op.drop_constraint(None, 'payloads', type_='foreignkey')
    op.drop_column('payloads', 'modified_by')
    op.drop_column('payloads', 'created_by')
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.drop_column('environments', 'modified_by')
    op.drop_column('environments', 'created_by')
    # ### end Alembic commands ###
