"""empty message

Revision ID: 67cb3c63edeb
Revises: 3cbc942325ad
Create Date: 2022-06-09 16:52:05.171939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cb3c63edeb'
down_revision = '3cbc942325ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'comment')
    # ### end Alembic commands ###
