"""empty message

Revision ID: 6ccb841a5869
Revises: 67cb3c63edeb
Create Date: 2022-06-14 01:54:59.355381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccb841a5869'
down_revision = '67cb3c63edeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_admin', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('members', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_constraint('projects_user_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['project_admin'], ['id'])
    op.create_foreign_key(None, 'projects', 'organization', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['members'], ['id'])
    op.drop_column('projects', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_fkey', 'projects', 'users', ['user'], ['id'])
    op.drop_column('projects', 'organization_id')
    op.drop_column('projects', 'members')
    op.drop_column('projects', 'project_admin')
    # ### end Alembic commands ###
