"""empty message

Revision ID: 74d815edf9ba
Revises: 293c34ca1e1e
Create Date: 2022-06-01 20:17:32.065976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74d815edf9ba'
down_revision = '293c34ca1e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testsuite', sa.Integer(), nullable=True),
    sa.Column('testcase', sa.String(length=256), nullable=False),
    sa.Column('resp', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['testsuite'], ['testsuites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp')
    # ### end Alembic commands ###
