"""empty message

Revision ID: 9770cdc500cb
Revises: 74d815edf9ba
Create Date: 2022-06-03 15:20:12.832597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9770cdc500cb'
down_revision = '74d815edf9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('testcase_id', sa.Integer(), nullable=False),
    sa.Column('testsuite_id', sa.Integer(), nullable=False),
    sa.Column('payload_used', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ),
    sa.ForeignKeyConstraint(['testsuite_id'], ['testsuites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
