"""empty message

Revision ID: 9aa282618f04
Revises: 2773ce6312f0
Create Date: 2022-07-27 14:27:13.401965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa282618f04'
down_revision = '2773ce6312f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('endpoints_name_key', 'endpoints', type_='unique')
    op.drop_constraint('environments_name_key', 'environments', type_='unique')
    op.drop_constraint('headers_name_key', 'headers', type_='unique')
    op.drop_constraint('payloads_name_key', 'payloads', type_='unique')
    op.drop_constraint('projects_name_key', 'projects', type_='unique')
    op.drop_constraint('testcases_name_key', 'testcases', type_='unique')
    op.drop_constraint('testdata_name_key', 'testdata', type_='unique')
    op.drop_constraint('testsuites_name_key', 'testsuites', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('testsuites_name_key', 'testsuites', ['name'])
    op.create_unique_constraint('testdata_name_key', 'testdata', ['name'])
    op.create_unique_constraint('testcases_name_key', 'testcases', ['name'])
    op.create_unique_constraint('projects_name_key', 'projects', ['name'])
    op.create_unique_constraint('payloads_name_key', 'payloads', ['name'])
    op.create_unique_constraint('headers_name_key', 'headers', ['name'])
    op.create_unique_constraint('environments_name_key', 'environments', ['name'])
    op.create_unique_constraint('endpoints_name_key', 'endpoints', ['name'])
    # ### end Alembic commands ###
