"""empty message

Revision ID: 9eefa59bbab4
Revises: f2c8573a14db
Create Date: 2022-07-19 11:54:28.454275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eefa59bbab4'
down_revision = 'f2c8573a14db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'modified_by')
    op.drop_column('projects', 'created_by')
    # ### end Alembic commands ###
