"""empty message

Revision ID: a35716e87c02
Revises: 9895632fddd1
Create Date: 2022-05-23 16:21:35.483398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35716e87c02'
down_revision = '9895632fddd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testsuites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('testsuite_testcase',
    sa.Column('testsuite_id', sa.Integer(), nullable=True),
    sa.Column('testcase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ),
    sa.ForeignKeyConstraint(['testsuite_id'], ['testsuites.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testsuite_testcase')
    op.drop_table('testsuites')
    # ### end Alembic commands ###
