"""empty message

Revision ID: a8f82d85060d
Revises: fa6f5d6f8b12
Create Date: 2022-06-05 19:18:29.217017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f82d85060d'
down_revision = 'fa6f5d6f8b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint('results_project_fkey', 'results', type_='foreignkey')
    op.create_foreign_key(None, 'results', 'projects', ['project_id'], ['id'])
    op.drop_column('results', 'project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.create_foreign_key('results_project_fkey', 'results', 'projects', ['project'], ['id'])
    op.drop_column('results', 'project_id')
    # ### end Alembic commands ###
