"""empty message

Revision ID: ca03b7af9fa8
Revises: 9eefa59bbab4
Create Date: 2022-07-19 12:35:30.694389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca03b7af9fa8'
down_revision = '9eefa59bbab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_member',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], )
    )
    op.drop_constraint('projects_members_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('members', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_members_fkey', 'projects', 'users', ['members'], ['id'])
    op.drop_table('project_member')
    # ### end Alembic commands ###
