"""empty message

Revision ID: e6d54f35979a
Revises: 2948ed11a0f6
Create Date: 2022-07-20 11:18:48.487352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d54f35979a'
down_revision = '2948ed11a0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headers', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('headers', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'headers', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'headers', 'users', ['modified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'headers', type_='foreignkey')
    op.drop_constraint(None, 'headers', type_='foreignkey')
    op.drop_column('headers', 'modified_by')
    op.drop_column('headers', 'created_by')
    # ### end Alembic commands ###
