"""empty message

Revision ID: f2c8573a14db
Revises: 0d5c016557a4
Create Date: 2022-07-19 11:26:13.720971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c8573a14db'
down_revision = '0d5c016557a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('endpoints_created_by_fkey', 'endpoints', type_='foreignkey')
    op.drop_constraint('endpoints_modified_by_fkey', 'endpoints', type_='foreignkey')
    op.drop_column('endpoints', 'created_by')
    op.drop_column('endpoints', 'modified_by')
    op.drop_constraint('projects_organization_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_organization_id_fkey', 'projects', 'organization', ['organization_id'], ['id'])
    op.add_column('endpoints', sa.Column('modified_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('endpoints', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('endpoints_modified_by_fkey', 'endpoints', 'users', ['modified_by'], ['id'])
    op.create_foreign_key('endpoints_created_by_fkey', 'endpoints', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
