"""empty message

Revision ID: fa6f5d6f8b12
Revises: 9770cdc500cb
Create Date: 2022-06-03 15:22:25.654548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6f5d6f8b12'
down_revision = '9770cdc500cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'results', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'user')
    # ### end Alembic commands ###
